name: Build and push Docker image

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add environment variables
        run: |
          cd TouristarConsumer
          openssl base64 -d <<< "${{ secrets.APP_SETTINGS_BASE_64 }}" -out appsettings.json -A

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag touristar-consumer

      - name: Tag the Docker image
        run: docker tag touristar-consumer karimtouristar/touristar-consumer

      - name: Push the Docker image to the registry
        run: docker push karimtouristar/touristar-consumer